apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app
  namespace: fastapi-ns
spec:
  replicas: 2
  imagePullSecrets: # ← ADD THIS
    - name: dockerhub-secret # ← ADD THIS
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: bibekk477/fastapi-devops-ci-cd:latest
          ports:
            - containerPort: 8000
